image: node:latest

stages:         
  - install
  - build
  - test
  - deploy

install:   
  stage: install
  script:
    - npm install
    - echo "Installing is done!"
  artifacts:
    paths:
      - node_modules/

lint-job:   
  stage: test    
  script:
    - npm run lint
    - echo "Linting code running... ."

prettier-job:   
  stage: test    
  script:
    - npm run prettier
    - echo "Prettier code running... ."

testing-job:   
  stage: test    
  script:
    - npm run test
    - echo "Testing from Jest code running... ."

build:          
  stage: build
  script:
    - npm run build
  artifacts:
    paths:
      - out/
  rules:
      - if: "$CI_COMMIT_BRANCH == 'main'"

deploy:
  stage: deploy
  script:
    - npx netlify-cli deploy --site $NETLIFY_SITE_ID --auth $NETLIFY_AUTH_TOKEN --prod
