name: tdw-mp1-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions

on: 
  push: 
    branches: [main]
  pull_request:
    branches: [main]


jobs:
  
  job1-install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - run: echo "The first job is install."
 
  job2-lint:
    runs-on: ubuntu-latest
    needs: [job1-install]
    steps:
      - run: echo "The third job is linter."
  
  job3-prettier:
    runs-on: ubuntu-latest
    needs: [job1-install]
    steps:
      - run: echo "The third job is prettier."
 
  job4-jest:
    runs-on: ubuntu-latest
    needs: [job1-install]
    steps:
      - run: echo "The second job is testing jest."
  
  job5-build:
    runs-on: ubuntu-latest
    needs: [job4-jest]
    steps:
      - run: echo "This job is build and goes after test jest"
  
  job6-deploy:
    runs-on: ubuntu-latest
    needs: [job5-build]
    steps:
      - run: echo "This is the final job and is deploy"
  
