name: tdw-mp1-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions

on: 
  push: 
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  install:
    runs on: ubuntu-latest
    steps:
      - name: Chekout repository
        uses: actions/checkout@v3
        
      - name: Dependencies cache
        id: cache-npm
        uses: actions/cache@v3
        env: 
          cache-name: cahce-node-modules
        with: 
          path: node_modules/
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.OS }}-npm-cache-
      
      - name: Install dependencies
        run: npm install
     
