name: tdw-mp1-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions

on: 
  push: 
    branches: [main]
  pull_request:
    branches: [main]


jobs:
  
  job1-install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
      - uses: actions/checkout@v3
    
      - name: dependencies cache
        id: cache-npm
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules/
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-npm-cache-
      - if: ${{ steps.cache-npm.outputs.cache-hit != 'true' }}
        name: Install dependencies
        continue-on-error: false
        run: npm install

     
     
