name: tdw-mp1-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions

on: 
  push: 
    branches: [main]
  pull_request:
    branches: [main]


jobs:
  
  job1-install:
    runs-on: ubuntu-latest
    steps:
      - run: echo "The first job is install."
 
  job2-test-jest:
    runs-on: ubuntu-latest
    needs: [job1-install]
    steps:
      - run: echo "The second job is testing jest."
     
