name: tdw-mp1-github-actions
run-name: ${{ github.actor }} is trying to survive at life.

on: 
  push: 
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: '0 0 * * *'

env:
  CONTENTFUL_SPACE_ID: ${{secrets.CONTENTFUL_SPACE_ID}}
  CONTENTFUL_ACCESS_TOKEN: ${{secrets.CONTENTFUL_ACCESS_TOKEN}}

jobs:
  
  job1-install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - run: echo "The first job is install." 
      - name: dependencies cache
        id: cache-npm
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules/
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-npm-cache-  
      - if: ${{ steps.cache-npm.outputs.cache-hit != 'true' }}
        name: Install dependencies
        continue-on-error: false
        run: npm install 
 
  job2-lint:
    runs-on: ubuntu-latest
    needs: job1-install
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - run: echo "The second job is linter."
      - name: dependencies cache
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules/
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
      - name: test linter
        run: npm run lint
  
  job3-prettier:
    runs-on: ubuntu-latest
    needs: job1-install
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - run: echo "The third job is prettier."
      - name: dependencies cache
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules/
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
      - name: test prettier
        run: npm run prettier
 
  job4-jest:
    runs-on: ubuntu-latest
    needs: job1-install
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - run: echo "The fourth job is testing jest."
      - name: dependencies cache
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules/
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
      - name: test jest
        run: npm run test
  
  job5-build:
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    needs: [job1-install,job2-lint,job3-prettier,job4-jest]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - run: echo "This job number five is build and goes after all the other jobs"
      
      - name: dependencies cache
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules/
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
      - run: npm run build
      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: build-files
          path: out/

  job6-deploy:
    runs-on: ubuntu-latest
    needs: job5-build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - run: echo "This is the final job and it is deploy"
      - name: dependencies cache
        uses: actions/cache@v3  
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules/
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
      - name: Download a Build Artifact
        uses: actions/download-artifact@v3.0.1
        with:
          name: build-files
          path: out/
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        
      - run: npx netlify-cli deploy 
